### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by Chasen-7** [jupyter-server/jupyter-scheduler#372] opened 2023-05-17 03:58 UTC
File "miniconda3/envs/py38_research/lib/python3.8/site-packages/jupyter_scheduler/executors.py", line 58, in process
    self.execute()
  File "miniconda3/envs/py38_research/lib/python3.8/site-packages/jupyter_scheduler/executors.py", line 138, in execute
    ep.preprocess(nb)
  File "miniconda3/envs/py38_research/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 80, in preprocess
    with self.setup_kernel():
  File "miniconda3/envs/py38_research/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "miniconda3/envs/py38_research/lib/python3.8/site-packages/nbclient/client.py", line 561, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "miniconda3/envs/py38_research/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "miniconda3/envs/py38_research/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "miniconda3/envs/py38_research/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "miniconda3/envs/py38_research/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
miniconda3/envs/py38_research/lib/python3.8/site-packages/jupyter_scheduler/executors.py:62: RuntimeWarning: coroutine 'NotebookClient.async_start_new_kernel' was never awaited
  self.on_failure(e)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

I got this error which caused failure on every scheduled job

**Comment by JasonWeill** [comment] 2023-06-06 21:26
Closing as a duplicate of #330.

**Closed by JasonWeill** 2023-06-06 21:26 UTC
Labels: bug
