### ISSUE TITLE
Support for multiple output files

### ISSUE THREAD

**Issue by andrii-i** [jupyter-server/jupyter-scheduler#408] opened 2023-07-26 02:13 UTC
### Problem

Currently running a job outputs a single notebook with all cells executed with no support for multiple output files

### Proposed Solution

Support for multiple output files

**Comment by JasonWeill** [comment] 2023-08-14 16:46
Closing as duplicate of #349, targeted for release in 2.2.0.

**Closed by JasonWeill** 2023-08-14 16:46 UTC
Labels: enhancement
