### ISSUE TITLE
Upgrade to sqlalchemy-2.0.15 and ipython-sql-0.5.0

### ISSUE THREAD

**Issue by janzinho** [jupyter-server/jupyter-scheduler#376] opened 2023-06-01 14:24 UTC
### Problem

Hi, 
I can only run jupyter-scheduler when using sqlalchemy==1.4.48 and ipython-sql==0.4.1 which are both old versions.

### Proposed Solution

It would be great if you could upgrade jupyter-scheduler to be compatible to sqlalchemy-2.0.15 and ipython-sql-0.5.0.

Best,
Jan

**Comment by janzinho** [comment] 2023-06-15 13:02
Thank you for answer. I think I don’t have the necessary know-how to create a pull request with a solution proposal. Is there any other way I can help or contribute?

**Comment by andrii-i** [comment] 2024-09-03 18:24
Hi @janzinho. This was fixed by PR #521 (fixed issue #478 which was a duplicate of this issue but it slipped past us) so any Jupyter Scheduler >= 2.7 would depend on SQLAlchemy >= 2.

**Closed by andrii-i** 2024-09-03 18:24 UTC
Labels: enhancement
